/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#0b1c30",
        "on-primary": "#ffffff",
        "primary-container": "#131b2e",
        "on-tertiary-container": "#75859d",
        "inverse-surface": "#2d3133",
        "surface-container-high": "#e6e8ea",
        "surface-tint": "#565e74",
        "surface-bright": "#f7f9fb",
        "secondary-container": "#6cf8bb",
        "on-secondary-container": "#00714d",
        "inverse-primary": "#bec6e0",
        "background": "#f7f9fb",
        "on-tertiary-fixed-variant": "#38485d",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed-dim": "#b7c8e1",
        "secondary": "#006c49",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed": "#6ffbbe",
        "on-primary-fixed": "#131b2e",
        "on-primary-container": "#7c839b",
        "primary": "#000000",
        "on-surface-variant": "#45464d",
        "on-secondary-fixed": "#002113",
        "surface-container": "#eceef0",
        "surface-dim": "#d8dadc",
        "on-surface": "#191c1e",
        "primary-fixed": "#dae2fd",
        "tertiary-container": "#0b1c30",
        "secondary-fixed-dim": "#4edea3",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#bec6e0",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "outline-variant": "#c6c6cd",
        "tertiary": "#000000",
        "on-secondary-fixed-variant": "#005236",
        "surface-variant": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#d3e4fe",
        "on-secondary": "#ffffff",
        "outline": "#76777d",
        "surface-container-highest": "#e0e3e5",
        "surface": "#f7f9fb"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "margin-mobile": "16px",
        "sidebar-width": "280px",
        "gutter": "24px",
        "container-max": "1440px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
